fileapp/urls.py
from django.urls import path
from . import views


app_name = "fileapp"

urlpatterns = [

    path("", views.index),
    path("upload", views.send_fills, name="uploads")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("fileapp.urls", namespace="fileapp"))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fileapp/models.py
from django.db import models

# Create your models here.


class myuploadfile(models.Model):
    f_name = models.CharField(max_length=255)
    myfiles = models.FileField(upload_to="")

    def __str__(self):
        return self.f_name

fileapp/views.py
from unicodedata import name
from django.shortcuts import render, HttpResponse

from . models import myuploadfile

# Create your views here.


def index(request):
    return render(request, "index.html")


def send_fills(request):
    if request.method == "POST":
        name = request.POST.get("filename")
        myfile = request.FILES.getlist("uploadfoles")
        for f in myfile:
            myuploadfile(f_name=name, myfiles=f).save()

        return HttpResponse("ok")

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="{% url 'fileapp:uploads' %}" method="POST" enctype="multipart/form-data">
        <input type="text" name="filename" placeholder="enter your file name">
        <input type="file" multiple name="uploadfoles">
        {% csrf_token %}
        <button type="submit">File Upload</button>

    </form>

</body>

</html>